add 2 function,format html
htmlacademy-javascript/810133-keksobooking-22 pull request #2
Opened 2021-02-04 18:20 UTC by vitaliy-ratnikov

2021-02-05 06:53 UTC, craz3r requested changes

2021-02-05 06:53 UTC, craz3r commented on js/main.js
> +const getRandomMinMaxInt = function (min, max) {
Эта функция не будет работать с отрицательным диапазоном. Так как нужно чтобы функция генерировала только положительные числа, то надо сделать соответствующую проверку аргументов

2021-02-05 06:53 UTC, craz3r commented on js/main.js
> +const getRandomInt = function (min, max, digits) {
В этой функции должны быть реализованы требования предыдущей функции, min > max, и положительный диапазон. Я бы посоветовал начать выполнение задания именно с этой функции, так как по сути первая функция является частным случаем второй, и их поведение можно обобщить, переиспользуя при этом код

2021-02-05 18:57 UTC, vitaliy-ratnikov reviewed
Поправил функции

2021-02-06 10:35 UTC, craz3r approved these changes

2021-02-06 10:35 UTC, merged